name: ${project.name}
main: ${project.main}
version: ${project.version}
softdepend: ${project.softdepends}
author: ${project.authors}

commands:
  faq:
    usage: /<command> [<player>] <FAQ Name>
    permission: autofaq.use
  autofaq:
    usage: /<command> reload
    permissions: autofaq.admin

permissions:
  autofaq.admin:
    default: op
    children:
      autofaq.use.others: true

  autofaq.use.others:
    default: op

  autofaq.use:
    default: true
